interface ZIF_EXCEL_BOOK_PROPERTIES
  public .


  data CREATOR type ZEXCEL_CREATOR .
  data LASTMODIFIEDBY type ZEXCEL_CREATOR .
  data CREATED type TIMESTAMPL .
  data MODIFIED type TIMESTAMPL .
  data TITLE type ZEXCEL_TITLE .
  data SUBJECT type ZEXCEL_SUBJECT .
  data DESCRIPTION type ZEXCEL_DESCRIPTION .
  data KEYWORDS type ZEXCEL_KEYWORDS .
  data CATEGORY type ZEXCEL_CATEGORY .
  data COMPANY type ZEXCEL_COMPANY .
  data APPLICATION type ZEXCEL_APPLICATION .
  data DOCSECURITY type ZEXCEL_DOCSECURITY .
  data SCALECROP type ZEXCEL_SCALECROP .
  data LINKSUPTODATE type FLAG .
  data SHAREDDOC type FLAG .
  data HYPERLINKSCHANGED type FLAG .
  data APPVERSION type ZEXCEL_APPVERSION .

  methods INITIALIZE .
endinterface.
