interface ZIF_EXCEL_SHEET_PROTECTION
  public .


  data AUTO_FILTER type ZEXCEL_SHEET_PROTECTION_BOOL .
  constants C_ACTIVE type ZEXCEL_SHEET_PROTECTION_BOOL value '1'. "#EC NOTEXT
  constants C_NOACTIVE type ZEXCEL_SHEET_PROTECTION_BOOL value '0'. "#EC NOTEXT
  constants C_PROTECTED type ZEXCEL_SHEET_PROTECTION value 'X'. "#EC NOTEXT
  constants C_UNPROTECTED type ZEXCEL_SHEET_PROTECTION value ''. "#EC NOTEXT
  data DELETE_COLUMNS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data DELETE_ROWS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data FORMAT_CELLS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data FORMAT_COLUMNS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data FORMAT_ROWS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data INSERT_COLUMNS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data INSERT_HYPERLINKS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data INSERT_ROWS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data OBJECTS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data PASSWORD type ZEXCEL_AES_PASSWORD .
  data PIVOT_TABLES type ZEXCEL_SHEET_PROTECTION_BOOL .
  data PROTECTED type ZEXCEL_SHEET_PROTECTION .
  data SCENARIOS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data SELECT_LOCKED_CELLS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data SELECT_UNLOCKED_CELLS type ZEXCEL_SHEET_PROTECTION_BOOL .
  data SHEET type ZEXCEL_SHEET_PROTECTION_BOOL .
  data SORT type ZEXCEL_SHEET_PROTECTION_BOOL .

  methods INITIALIZE .
endinterface.
