interface ZIF_EXCEL_SHEET_PROPERTIES
  public .


  constants C_HIDDEN type ZEXCEL_SHEET_HIDDEN value 'X'. "#EC NOTEXT
  constants C_VERYHIDDEN type ZEXCEL_SHEET_HIDDEN value '2'. "#EC NOTEXT
  constants C_HIDEZERO type ZEXCEL_SHEET_SHOWZEROS value ''. "#EC NOTEXT
  constants C_SHOWZERO type ZEXCEL_SHEET_SHOWZEROS value 'X'. "#EC NOTEXT
  constants C_VISIBLE type ZEXCEL_SHEET_HIDDEN value ''. "#EC NOTEXT
  data HIDDEN type ZEXCEL_SHEET_HIDDEN .
  data SHOW_ZEROS type ZEXCEL_SHEET_SHOWZEROS .
  data STYLE type ZEXCEL_CELL_STYLE .
  data ZOOMSCALE type ZEXCEL_SHEET_ZOOMSCALE .
  data ZOOMSCALE_NORMAL type ZEXCEL_SHEET_ZOOMSCALE .
  data ZOOMSCALE_PAGELAYOUTVIEW type ZEXCEL_SHEET_ZOOMSCALE .
  data ZOOMSCALE_SHEETLAYOUTVIEW type ZEXCEL_SHEET_ZOOMSCALE .
  data SUMMARYBELOW type ZEXCEL_SHEET_SUMMARY .
  constants C_BELOW_ON type ZEXCEL_SHEET_SUMMARY value 1. "#EC NOTEXT
  constants C_BELOW_OFF type ZEXCEL_SHEET_SUMMARY value 0. "#EC NOTEXT
  data SUMMARYRIGHT type ZEXCEL_SHEET_SUMMARY .
  constants C_RIGHT_ON type ZEXCEL_SHEET_SUMMARY value 1. "#EC NOTEXT
  constants C_RIGHT_OFF type ZEXCEL_SHEET_SUMMARY value 0. "#EC NOTEXT
  data SELECTED type ZEXCEL_SHEET_SELECTED .
  constants C_SELECTED type ZEXCEL_SHEET_SELECTED value 'X'. "#EC NOTEXT
  data HIDE_COLUMNS_FROM type ZEXCEL_CELL_COLUMN_ALPHA .

  methods INITIALIZE .
  methods GET_STYLE
    returning
      value(EP_STYLE) type ZEXCEL_CELL_STYLE .
  methods SET_STYLE
    importing
      !IP_STYLE type ZEXCEL_CELL_STYLE .
endinterface.
