interface ZIF_EXCEL_BOOK_PROTECTION
  public .


  constants C_LOCKED type ZEXCEL_BOOK_PROTECTION value '1'. "#EC NOTEXT
  constants C_PROTECTED type ZEXCEL_BOOK_PROTECTION value 'X'. "#EC NOTEXT
  constants C_UNLOCKED type ZEXCEL_BOOK_PROTECTION value '0'. "#EC NOTEXT
  constants C_UNPROTECTED type ZEXCEL_BOOK_PROTECTION value ''. "#EC NOTEXT
  data LOCKREVISION type ZEXCEL_BOOK_PROTECTION .
  data LOCKSTRUCTURE type ZEXCEL_BOOK_PROTECTION .
  data LOCKWINDOWS type ZEXCEL_BOOK_PROTECTION .
  data PROTECTED type ZEXCEL_BOOK_PROTECTION .
  data REVISIONSPASSWORD type ZEXCEL_AES_PASSWORD .
  data WORKBOOKPASSWORD type ZEXCEL_AES_PASSWORD .

  methods INITIALIZE .
endinterface.
